import React from 'react';

export default function TermsOfServicePage() {
  return (
    <main className="max-w-3xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="prose prose-blue">
        <h1>Terms of Service</h1>
        <p><strong>Effective Date:</strong> June 3, 2025</p>
        <p>Welcome to CeyLog. These Terms of Service govern your use of our platform and services.</p>
        <h2>1. Acceptance of Terms</h2>
        <p>By registering or using the platform, you agree to be bound by these terms. If you do not agree, you may not use the service.</p>
        <h2>2. Description of Service</h2>
        <p>CeyLog provides AI-powered market analysis, buyer matchmaking, and product visibility tools for users in the import/export and logistics sectors.</p>
        <h2>3. User Responsibilities</h2>
        <ul>
          <li>Provide accurate information during registration.</li>
          <li>Keep login credentials secure.</li>
          <li>Not upload or submit unlawful or harmful content.</li>
          <li>Use the services only for legitimate business purposes.</li>
        </ul>
        <h2>4. Subscription and Payments</h2>
        <ul>
          <li>Some features are available through a paid Pro Membership.</li>
          <li>All payments are securely handled via Stripe.</li>
          <li>Refunds are only provided in case of technical failure or service error.</li>
        </ul>
        <h2>5. Intellectual Property</h2>
        <p>All content generated by the platform (reports, analysis, tools) is the intellectual property of CeyLog and may not be redistributed without permission.</p>
        <h2>6. Service Modifications</h2>
        <p>We reserve the right to modify or discontinue any part of the service at any time without notice.</p>
        <h2>7. Termination</h2>
        <p>Accounts may be suspended or terminated if these terms are violated or if fraudulent activity is detected.</p>
        <h2>8. Limitation of Liability</h2>
        <p>CeyLog is not responsible for direct or indirect losses resulting from the use of the platform.</p>
        <h2>9. Governing Law</h2>
        <p>These terms are governed by UK law. Any disputes will be handled in UK courts.</p>
        <h2>10. Contact</h2>
        <p>If you have questions about these terms, contact: contact@ceylanlogistics.co.uk</p>
        <hr />
        <p>Copyright © CeyLog 2025. All rights reserved.</p>
      </div>
    </main>
  );
} 